apiVersion: v2
appVersion: "v7.6.1"
description: A Helm chart for the Prometheus Fastly Exporter
name: prometheus-fastly-exporter
version: 0.3.0
keywords:
  - metrics
  - fastly
  - monitoring
home: https://github.com/fastly/fastly-exporter
maintainers:
  - name: arslanbekov
    email: arslanbekov@gmail.com
