---
scrapeConfigs: null

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: "self"
        static_configs:
          - targets:
              - "localhost:9090"
            labels:
              foo: "bar"

extraScrapeConfigs: |
  - job_name: "custom-job"
    static_configs:
      - targets:
          - "localhost:9191"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
