{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "prometheus-smartctl-exporter.fullname" . }}.rules
  labels:
    {{- include "prometheus-smartctl-exporter.labels" . | nindent 4 }}
{{- if ne (len .Values.prometheusRules.extraLabels) 0 }}
{{ toYaml .Values.prometheusRules.extraLabels | indent 4 }}
{{- end }}
{{- if .Values.prometheusRules.namespace }}
  namespace: {{ .Values.prometheusRules.namespace }}
{{- end }}
spec:
  groups:
  - name: smartctl-exporter.rules
    rules:
{{- range $key, $value := .Values.prometheusRules.rules }}
{{- if $.Values.prometheusRules.alertLabels }}
{{- $_ := mustMerge .labels $.Values.prometheusRules.alertLabels }}
{{- end }}
    - alert: {{ $key }}
      {{- toYaml $value | nindent 6 }}
{{- end }}
{{- end }}
