{{- if .Values.server.verticalAutoscaler.enabled -}}
{{- $fullname := include "prometheus.server.fullname" . }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" $fullname "vpa" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "prometheus.namespace" . }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
{{- if .Values.server.statefulSet.enabled }}
    kind: StatefulSet
{{- else }}
    kind: Deployment
{{- end }}
    name: {{ template "prometheus.server.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.server.verticalAutoscaler.updateMode | default "Off" | quote }}
  resourcePolicy:
    containerPolicies: {{ .Values.server.verticalAutoscaler.containerPolicies | default list | toYaml | trim | nindent 4 }}
{{- end -}}
