{{- if .Values.rbac.create }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "prometheus-kafka-exporter.fullname" . }}
  labels:
    {{- include "prometheus-kafka-exporter.labels" . | nindent 4 }}
  namespace: {{ include "prometheus-kafka-exporter.namespace" . }}
{{- if and .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "prometheus-kafka-exporter.fullname" . }}]
{{- end }}
{{- end }}
