{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-kafka-exporter.fullname" . }}
  {{- if .Values.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ include "prometheus-kafka-exporter.namespace" . }}
  {{- end }}
  labels:
    {{- include "prometheus-kafka-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.prometheus.serviceMonitor.jobLabel }}
  jobLabel: {{.Values.prometheus.serviceMonitor.jobLabel }}
  {{- end }}
{{- if .Values.prometheus.serviceMonitor.targetLabels }}
  targetLabels:
{{- range .Values.prometheus.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-kafka-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: exporter-port
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
    {{- if .Values.prometheus.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- with .Values.prometheus.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
