apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-kafka-exporter.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-kafka-exporter.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ include "prometheus-kafka-exporter.namespace" . }}
spec:
  type: {{ .Values.service.type }}
{{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: exporter-port
      protocol: TCP
      name: exporter-port
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector: {{ include "prometheus-kafka-exporter.selectorLabels" . | nindent 4 }}
