apiVersion: v2
appVersion: "0.13.1"
description: A Helm chart for prometheus postgres-exporter
name: prometheus-postgres-exporter
version: 5.0.0
home: https://github.com/prometheus-community/postgres_exporter
sources:
- https://github.com/prometheus-community/postgres_exporter
keywords:
- postgresql
- prometheus
- exporter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: rootsandtrees@posteo.de
  name: zeritti
type: application
