{{- if not .Values.config.externalQueries.enabled }}
{{- if or .Values.config.queries .Values.config.userQueries }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-postgres-exporter.name" . }}
    chart: {{ template "prometheus-postgres-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ template "prometheus-postgres-exporter.namespace" . }}
data:
  allow-snippet-annotations: "false"
  config.yaml: |
    {{- tpl (mergeOverwrite (tpl .Values.config.queries . | fromYaml) (tpl .Values.config.userQueries . | fromYaml) | toYaml) . | nindent 4 }}
{{- end }}
{{- end }}
