{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "prometheus-postgres-exporter.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-postgres-exporter.name" . }}
    chart: {{ template "prometheus-postgres-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: {{ template "prometheus-postgres-exporter.namespace" . }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "prometheus-postgres-exporter.name" . }}
      release: {{ .Release.Name }}
{{- end }}
