---
extraManifests:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: '{{ include "prometheus-postgres-exporter.fullname" . }}-extra-cm1'
  data:
    extra-data: "value1"
- apiVersion: v1
  kind: Secret
  metadata:
    name: '{{ include "prometheus-postgres-exporter.fullname" . }}-extra-secret1'
  stringData:
    secret: "value"
