apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-json-exporter.fullname" . }}
  namespace: {{ include "prometheus-json-exporter.namespace" . }}
  labels:
    {{- include "prometheus-json-exporter.labels" . | nindent 4 }}
data:
  allow-snippet-annotations: "false"
  config.yml: |
  {{ .Values.configuration.config | nindent 4 }}
